const eventTypes = ['ALL', 'A3', 'A5', 'AF', 'AL', 'MX', 'RI', 'SE'];
const eventNames = { A3: 'Alternative 3\'', A5: 'Alternative 5\'', AF: 'Alternative first', AL: 'Alternative last', MX: 'Mutually exclusive', RI: 'Retained intron', SE: 'Skipped exon' };
const eventColors = { A3: '#4fb78c', A5: '#78b0ee', AF: '#e9b84f', AL: '#ef786c', MX: '#8f88db', RI: '#7bc6a4', SE: '#c4d2cc' };
const sampleEvents = [
  ['ENSMUSG00000025900.13;SE:chr1:4293012-4311270', 'Ttn', 'SE', 'E11.5 → E16.5', '0.82', '+0.46', '2.1e-08'],
  ['ENSMUSG00000033845.7;AF:chr7:127883-130112', 'Mef2c', 'AF', 'E11.5 → E16.5', '0.18', '-0.39', '8.4e-07'],
  ['ENSMUSG00000067274.6;RI:chr5:991233-994814', 'Ryr2', 'RI', 'E12.5 → P0', '0.67', '+0.34', '1.7e-05'],
  ['ENSMUSG00000037742.8;A3:chr9:214221-216087', 'Actc1', 'A3', 'E11.5 → E13.5', '0.41', '-0.31', '3.2e-05'],
  ['ENSMUSG00000029661.12;SE:chr2:663102-667720', 'Nrxn1', 'SE', 'E13.5 → E16.5', '0.75', '+0.29', '6.8e-05'],
  ['ENSMUSG00000022514.10;AL:chr8:772891-776230', 'Pkm', 'AL', 'E11.5 → P0', '0.29', '-0.28', '9.4e-05'],
  ['ENSMUSG00000022454.14;A5:chr11:401992-405381', 'Srsf3', 'A5', 'E12.5 → E15.5', '0.63', '+0.25', '1.2e-04'],
  ['ENSMUSG00000020186.9;MX:chr3:918221-923145', 'Mbnl1', 'MX', 'E13.5 → E16.5', '0.52', '-0.22', '2.7e-04'],
  ['ENSMUSG00000031972.11;AF:chr4:112221-114090', 'Tpm1', 'AF', 'E11.5 → E15.5', '0.71', '+0.21', '3.2e-04'],
  ['ENSMUSG00000028864.8;RI:chr6:331902-339412', 'Cacna1c', 'RI', 'E12.5 → P0', '0.22', '-0.20', '4.5e-04']
];

let selectedFiles = [];
let currentJobId = null;
let backendAvailable = false;

function iconRefresh(){ if(window.lucide) lucide.createIcons(); }
function showToast(message){ const toast=document.querySelector('#toast'); toast.querySelector('span').textContent=message; toast.classList.add('show'); setTimeout(()=>toast.classList.remove('show'),2600); }
async function detectBackend(){const status=document.querySelector('#engine-status');const dot=document.querySelector('.version-top .status-dot');try{const response=await fetch('/api/health',{cache:'no-store'});if(!response.ok)throw new Error('unavailable');const health=await response.json();backendAvailable=health.status==='ok';status.textContent=backendAvailable?'分析引擎在线':'GitHub Pages 演示模式';dot.classList.toggle('demo-mode',!backendAvailable);}catch{backendAvailable=false;status.textContent='GitHub Pages 演示模式';dot.classList.add('demo-mode');}const demo=document.querySelector('.demo-pill');if(demo)demo.lastChild.textContent=backendAvailable?' Local analysis':' Static demo';}

function makeBarChart(){
  const values=[[42,33,25,31,22,18,27],[34,28,22,27,19,16,25],[48,40,35,39,32,27,34],[27,25,21,24,17,15,20],[62,48,42,46,39,35,44],[54,41,37,43,31,28,39],[70,57,50,54,48,44,56]];
  document.querySelector('#bar-chart').innerHTML=values.map((group)=>`<div class="bar-group">${group.map((v,i)=>`<span class="bar ${i===0?'main':''}" style="height:${v*2.05}px"></span>`).join('')}</div>`).join('');
}
function makeDonutLegend(){
  const data=[['SE',31],['AF',23],['RI',14],['AL',10],['A3',9],['A5',8],['MX',5]];
  document.querySelector('#donut-legend').innerHTML=data.map(([type,value])=>`<div class="donut-item"><i style="background:${eventColors[type]}"></i><span>${type}</span><strong>${value}%</strong></div>`).join('');
}
function makeScatter(){
  const points=[[22,62,'#4a7cf0'],[28,54,'#4a7cf0'],[32,70,'#4a7cf0'],[39,45,'#4a7cf0'],[44,58,'#4a7cf0'],[49,36,'#eab64b'],[54,45,'#eab64b'],[58,29,'#eab64b'],[61,52,'#eab64b'],[68,34,'#ef786c'],[72,45,'#ef786c'],[77,23,'#ef786c'],[81,32,'#ef786c'],[87,18,'#ef786c'],[89,38,'#ef786c']];
  document.querySelector('#pca-chart').innerHTML=points.map(([x,y,c])=>`<i class="scatter-point" style="left:${x}%;top:${y}%;background:${c}"></i>`).join('');
}
function makeHeatmap(){
  const cells=[]; for(let row=0;row<8;row++){for(let col=0;col<20;col++){let score=(Math.sin(row*1.7+col*.57)+Math.cos(col*.31-row)+2)/4; const colors=['#eef5f1','#d5e9df','#aed8c5','#78c19e','#4fb78c','#247e5d']; cells.push(`<i class="heat-cell" style="background:${colors[Math.min(5,Math.floor(score*6))]}"></i>`);}} document.querySelector('#heatmap').innerHTML=cells.join('');
}
function makeVolcano(){
  let html=''; for(let i=0;i<98;i++){const left=5+Math.random()*90, top=55+Math.random()*38, color=i%2?'#4a7cf0':'#b3c6bc'; html+=`<i class="volcano-point" style="left:${left}%;top:${top}%;background:${color}"></i>`;} for(let i=0;i<52;i++){const left=5+Math.random()*44, top=7+Math.random()*39; html+=`<i class="volcano-point" style="left:${left}%;top:${top}%;background:#4a7cf0"></i>`;} for(let i=0;i<58;i++){const left=53+Math.random()*42, top=5+Math.random()*40; html+=`<i class="volcano-point" style="left:${left}%;top:${top}%;background:#ef786c"></i>`;} [[18,17,'Ptbp1'],[78,15,'Ttn'],[86,28,'Mef2c'],[30,28,'Ryr2']].forEach(([x,y,gene])=>html+=`<i class="volcano-point highlight" title="${gene}" style="left:${x}%;top:${y}%;background:${x>50?'#ef786c':'#4a7cf0'}"></i>`); document.querySelector('#volcano-chart').innerHTML=html;
}
function renderEventTabs(){ document.querySelector('#event-tabs').innerHTML=eventTypes.map(t=>`<button class="event-tab ${t==='ALL'?'active':''}" data-type="${t}">${t}</button>`).join(''); document.querySelectorAll('.event-tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.event-tab').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); renderTable(btn.dataset.type);})); }
function renderTable(type='ALL'){
  const search=(document.querySelector('#event-search')?.value||'').toLowerCase(); const direction=document.querySelector('#event-filter')?.value||'all';
  const rows=sampleEvents.filter(row=>(type==='ALL'||row[2]===type)&&(!search||row.join(' ').toLowerCase().includes(search))&&(direction==='all'||(direction==='up'?row[5].startsWith('+'):row[5].startsWith('-'))));
  document.querySelector('#events-table').innerHTML=rows.map(r=>`<tr><td class="event-id">${r[0]}</td><td class="gene">${r[1]}</td><td><span class="type-badge">${r[2]}</span></td><td>${r[3]}</td><td>${r[4]}</td><td class="${r[5].startsWith('+')?'dpsi-up':'dpsi-down'}">${r[5]}</td><td class="pval">${r[6]}</td><td><button class="row-action" title="查看事件"><i data-lucide="arrow-up-right"></i></button></td></tr>`).join(''); document.querySelector('#event-count').textContent=`Showing ${rows.length} of 1,824 significant events`; iconRefresh(); }
function bindNavigation(){ document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.page-view').forEach(v=>v.classList.remove('active'));document.querySelector(`#${btn.dataset.view}-view`).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});})); }
function bindUpload(){ const zone=document.querySelector('#upload-zone'), input=document.querySelector('#file-input'); const loadFiles=(files)=>{selectedFiles=[...files];if(!selectedFiles.length)return;const list=document.querySelector('#file-list');list.innerHTML='';selectedFiles.forEach(file=>{const ext=file.name.split('.').pop().toUpperCase();list.insertAdjacentHTML('beforeend',`<div class="file-row"><div class="file-type ${ext==='CSV'?'csv':''}">${ext}</div><div class="file-info"><strong>${file.name}</strong><span>已载入 · ${(file.size/1024/1024).toFixed(1)} MB</span></div><span class="file-state"><i data-lucide="check"></i></span></div>`);});iconRefresh();showToast(`已载入 ${selectedFiles.length} 个文件`);};document.querySelector('#browse-files').addEventListener('click',()=>input.click());zone.addEventListener('click',(e)=>{if(e.target.closest('button'))return;input.click();});input.addEventListener('change',()=>loadFiles(input.files));['dragenter','dragover'].forEach(event=>zone.addEventListener(event,e=>{e.preventDefault();zone.style.borderColor='#1d8b65';}));zone.addEventListener('dragleave',()=>zone.style.borderColor='');zone.addEventListener('drop',e=>{e.preventDefault();zone.style.borderColor='';loadFiles(e.dataTransfer.files);}); }
async function createJob(){ const config={data_source:document.querySelector('#data-source').value,species:document.querySelector('#species').value,design:document.querySelector('#design').value,comparison_mode:'baseline',event_type:'ALL',method:'empirical',p_value:Number(document.querySelector('input[aria-label="p value threshold"]').value),abs_dpsi:0.1,demo:selectedFiles.length===0,files:selectedFiles.map(file=>file.name)};if(!selectedFiles.length){return fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});}const form=new FormData();form.append('config',JSON.stringify(config));selectedFiles.forEach(file=>form.append('files',file,file.name));return fetch('/api/jobs',{method:'POST',body:form});}
async function loadResults(jobId){const response=await fetch(`/api/jobs/${jobId}/results`);if(!response.ok)return;const results=await response.json();const numbers=document.querySelectorAll('.metric-number');numbers[0].textContent=Number(results.metrics.total_events).toLocaleString();numbers[1].textContent=Number(results.metrics.significant_events).toLocaleString();numbers[2].textContent=String(results.metrics.sample_count).padStart(2,'0');numbers[3].textContent=Number(results.metrics.median_abs_dpsi).toFixed(2);if(Array.isArray(results.events)){sampleEvents.splice(0,sampleEvents.length,...results.events.map(row=>row.map(value=>String(value).replace(' -> ',' → '))));renderTable(document.querySelector('.event-tab.active')?.dataset.type||'ALL');}}
async function pollJob(jobId){const response=await fetch(`/api/jobs/${jobId}`);if(!response.ok)throw new Error('无法读取任务状态');const job=await response.json();const progress=Math.max(0,Math.min(100,job.progress||0));const statusTag=document.querySelector('.status-tag');document.querySelector('#progress-fill').style.width=`${progress}%`;document.querySelector('#progress-value').textContent=`${progress}%`;document.querySelector('#progress-text').textContent=job.status==='completed'?'7 / 7 stages complete':job.stage;if(statusTag)statusTag.innerHTML=`<span></span> ${job.status==='completed'?'COMPLETED':job.status==='failed'?'FAILED':'RUNNING'}`;if(job.status==='completed'){await loadResults(jobId);return job;}if(job.status==='failed')throw new Error(job.error||'ASTK 任务失败');await new Promise(resolve=>setTimeout(resolve,350));return pollJob(jobId);}
async function runStaticDemo(){const fill=document.querySelector('#progress-fill'),value=document.querySelector('#progress-value'),text=document.querySelector('#progress-text'),statusTag=document.querySelector('.status-tag');for(const [progress,stage] of [[12,'Input validation'],[26,'Metadata generation'],[48,'Seven-class event generation'],[68,'PSI quantification'],[88,'Differential splicing'],[100,'Report generation']]){fill.style.width=`${progress}%`;value.textContent=`${progress}%`;text.textContent=stage;if(statusTag)statusTag.innerHTML='<span></span> DEMO';await new Promise(resolve=>setTimeout(resolve,260));}text.textContent='7 / 7 demo stages complete';if(statusTag)statusTag.innerHTML='<span></span> DEMO READY';}
function bindRun(){document.querySelector('#run-analysis').addEventListener('click',async()=>{const button=document.querySelector('#run-analysis');button.disabled=true;button.innerHTML='<i data-lucide="loader-circle"></i>提交中';document.querySelector('#progress-fill').style.width='0%';document.querySelector('#progress-value').textContent='0%';iconRefresh();try{if(!backendAvailable){await runStaticDemo();button.innerHTML='<i data-lucide="check"></i>演示完成';showToast('当前为 GitHub Pages 演示模式，未上传或计算任何数据');return;}const response=await createJob();if(!response.ok){const error=await response.json();throw new Error(error.error||'任务提交失败');}const job=await response.json();currentJobId=job.id;const idNode=document.querySelector('.run-id strong');if(idNode)idNode.textContent=job.id;button.innerHTML='<i data-lucide="loader-circle"></i>运行中';iconRefresh();await pollJob(job.id);button.innerHTML='<i data-lucide="check"></i>分析完成';showToast('后端任务已完成，结果已更新');}catch(error){button.innerHTML='<i data-lucide="triangle-alert"></i>运行失败';showToast(error.message);}finally{button.disabled=false;iconRefresh();setTimeout(()=>{button.innerHTML='<i data-lucide="play"></i>运行分析';iconRefresh();},2400);}});document.querySelector('#reset-demo').addEventListener('click',()=>{selectedFiles=[];currentJobId=null;document.querySelector('#progress-fill').style.width='100%';document.querySelector('#progress-value').textContent='100%';showToast('演示数据已重置');});}
function bindExports(){document.querySelector('#download-report').addEventListener('click',()=>{if(!backendAvailable){showToast('GitHub Pages 仅展示演示结果，请使用 Docker 运行真实分析');return;}if(!currentJobId){showToast('请先运行一次分析任务');return;}window.location.href=`/api/jobs/${currentJobId}/download`;});document.querySelector('#export-results').addEventListener('click',()=>showToast(backendAvailable?'结果摘要导出将在报告 ZIP 中提供':'GitHub Pages 演示模式不导出真实结果'));document.querySelector('#export-events').addEventListener('click',()=>showToast(backendAvailable?'事件表导出将在报告 ZIP 中提供':'GitHub Pages 演示模式不导出真实结果'));document.querySelector('#load-heart').addEventListener('click',()=>{document.querySelector('[data-view="dashboard"]').click();showToast('Heart development 已加载到工作台');});}
async function init(){makeBarChart();makeDonutLegend();makeScatter();makeHeatmap();makeVolcano();renderEventTabs();renderTable();bindNavigation();bindUpload();bindRun();bindExports();document.querySelector('#event-search').addEventListener('input',()=>{const active=document.querySelector('.event-tab.active');renderTable(active?.dataset.type||'ALL');});document.querySelector('#event-filter').addEventListener('change',()=>{const active=document.querySelector('.event-tab.active');renderTable(active?.dataset.type||'ALL');});iconRefresh();await detectBackend();}
init();
